# Generated by Django 5.2.9 on 2026-01-04 07:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notification_time', models.TimeField(default=datetime.time(9, 0))),
                ('chrome_notification_time', models.TimeField(default=datetime.time(8, 30))),
                ('total_school_days', models.IntegerField(default=220)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('chrome_notifications_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
