# Generated by Django 5.2.9 on 2026-01-04 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='email_notification_time',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='email_notifications_enabled',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='chrome_notification_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
