# Generated by Django 5.2.9 on 2026-01-04 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userpreferences_email_notification_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='email_notification_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='chrome_notification_time',
            field=models.TimeField(default=datetime.time(8, 30)),
        ),
    ]
