# Generated by Django 5.2.9 on 2026-01-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpreferences_email_notification_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='email_notification_time',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='email_notifications_enabled',
        ),
    ]
