# Generated by Django 5.2.9 on 2026-01-04 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userpreferences_email_notification_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='chrome_notification_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
