# Generated by Django 5.2.9 on 2026-01-04 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userpreferences_chrome_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='chrome_notification_time',
            field=models.TimeField(default=datetime.time(6, 30)),
        ),
    ]
