# Generated by Django 5.2.9 on 2026-01-04 12:22

from django.db import migrations
import datetime


def update_notification_times(apps, schema_editor):
    UserPreferences = apps.get_model('accounts', 'UserPreferences')
    UserPreferences.objects.all().update(chrome_notification_time=datetime.time(6, 30))


def reverse_notification_times(apps, schema_editor):
    # Reverse operation - set back to 7:00 AM
    UserPreferences = apps.get_model('accounts', 'UserPreferences')
    UserPreferences.objects.all().update(chrome_notification_time=datetime.time(7, 0))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_update_default_notification_time'),
    ]

    operations = [
        migrations.RunPython(update_notification_times, reverse_notification_times),
    ]
