# Generated by Django 5.2.9 on 2026-01-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_notification_trigger_and_email_prefs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='email_notification_time',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='email_notifications_enabled',
        ),
    ]
